### PR TITLE
CI: re-enable tests against Julia 1.6

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by SoongNoonien** [comment]
Ok, so apparently we need to adjust the `range` calls. I wanted to make them consistent anyway. Sometimes we use `start:end` and sometimes `range(start, end)`. But I don't know if `start:end` works with 1.6.

**Comment by fingolfin** [comment]
`start:end` even works in 1.0

**Comment by fingolfin** [comment]
Add to this one. You can push to my branch

**Comment by SoongNoonien** [comment]
Hey, that did the trick already!

**Pull request merged**
